### ISSUE TITLE
Authentication with oauth2

### ISSUE THREAD

**Issue by iagogo** [shenzhencenter/google-ads-pb#13]
Hi I'm not sure it's an issue at all, but I really can't authenticate with an API KEY, in the documentation of google ads API they say you need to do it with oauth2. 

I can't authenticate with oauth2, I don't know if its not posible or just it's me (I suspect the last 👎 because I'm totally new in Go) but I dont have any problems in other languages, and I not sure at all this module it's compatible with oauth2 (if is compatible, would you please share an example of how to do it?), if not, I can't imagine how to use the API KEY I've created.

Cheers and sorry for my english!

**Comment by xnkjj** [comment]
Hi iagogo,

All Google Ads API calls must be authorized through OAuth2. Here is a example [get_account_information.go](https://github.com/shenzhencenter/google-ads-pb/blob/main/examples/account_management/get_account_information.go#L13) of using oauth2 access token to call Ads API.

Recommend to read the [OAuth2 guide](https://developers.google.com/google-ads/api/docs/oauth/overview).

Regards.
