### ISSUE TITLE
从google api 生成ads grpc失败

### ISSUE THREAD

**Issue by olderyi** [shenzhencenter/google-ads-pb#22]
你好,我从googleapi仓库

[https://github.com/googleapis/googleapis/tree/master/google/ads/googleads/v15](https://github.com/googleapis/googleapis/tree/master/google/ads/googleads/v15)

把ads/googleads/v15中的所有proto文件拉下来,修改了里面所有的go_package为

`option go_package = "x/ad/google/enums;enums";`

使用protoc生成go文件和grpc文件

`protoc --go_out=. --go_opt=module=x ./google/ads/googleads/v15/common/*`
`protoc --go_out=. --go_opt=module=x ./google/ads/googleads/v15/enums/*`
`protoc --go_out=. --go_opt=module=x ./google/ads/googleads/v15/errors/*`
`protoc --go_out=. --go_opt=module=x ./google/ads/googleads/v15/resources/*`
`protoc --go_out=. --go-grpc_out=. --go-grpc_opt=module=x --go_opt=module=x ./google/ads/googleads/v15/services/*`

成功生成了代码,在go mod init x 后进行go mod tidy ,goland没有报错提示
然后创建test用例,进行测试时提示

`ad\google\services\experiment_arm_service.pb.go:197:57: undefined: resources.ExperimentArm
ad\google\services\experiment_arm_service.pb.go:204:57: undefined: resources.ExperimentArm
ad\google\services\experiment_arm_service.pb.go:224:20: undefined: resources.ExperimentArm
ad\google\services\experiment_arm_service.pb.go:230:20: undefined: resources.ExperimentArm
ad\google\services\experiment_arm_service.pb.go:319:27: undefined: resources.ExperimentArm
ad\google\services\experiment_arm_service.pb.go:361:67: undefined: resources.ExperimentArm
ad\google\services\experiment_arm_service.pb.go:522:14: undefined: resources.ExperimentArm
ad\google\services\google_ads_service.pb.go:734:27: undefined: resources.ExperimentArm
ad\google\services\google_ads_service.pb.go:1893:54: undefined: resources.ExperimentArm
ad\google\services\google_ads_service.pb.go:8234:14: undefined: resources.ExperimentArm
ad\google\services\google_ads_service.pb.go:8234:14: too many errors`
 等大量结构体未定义

我确定目录路径是没有问题的,在goland中可以从报错提示的代码直接ctrl+左键定位到ExperimentArm结构体
这个项目在生成时有没有碰到过这个问题呢?
可以请教一下是怎么生成正常的go代码吗?

**Comment by xnkjj** [comment]
https://github.com/shenzhencenter/google-ads-pb/blob/main/.github/workflows/generator.yml#L73

**Comment by olderyi** [comment]
成功解决了感谢大佬
