### ISSUE TITLE
How to auto generate the access token with refresh token ?

### ISSUE THREAD

**Issue by khanakia** [shenzhencenter/google-ads-pb#29]
Let's assume I am running the API call and the access token expires in between so how do I auto-generate the new access token with the Refresh token?

Google's other APIs have this feature e.g. `google.golang.org/api/searchconsole/v1`

**Comment by ic-it** [comment]
You can try to use "golang.org/x/oauth2" package. I think it should work.
```go
	headers := metadata.Pairs(
		"developer-token", devToken,
	)
	outgCtx := metadata.NewOutgoingContext(ctx, headers)

	// New OAuth2 config
	config := &oauth2.Config{
		ClientID:     clientID,
		ClientSecret: clientSecret,
		Endpoint:     google.Endpoint,
	}

	// New OAuth2 token
	token := &oauth2.Token{
		RefreshToken: refreshToken,
	}
```

**Comment by khanakia** [comment]
Getting the below error when i pass the `opts` as a third argument to `adsServiceClient.Search` func

```go
import (
	"github.com/shenzhencenter/google-ads-pb/services"
	"google.golang.org/api/option"
	"google.golang.org/grpc/metadata"
)

// conn = *grpc.ClientConn
adsServiceClient := services.NewGoogleAdsServiceClient(conn)

return adsServiceClient.Search(outgCtx, &services.SearchGoogleAdsRequest{
  Query:                   query,
  CustomerId:              "1234",
}, opts)
```


```
cannot use opts (variable of type []option.ClientOption) as grpc.CallOption value in argument to adsServiceClient.Search: []option.ClientOption does not implement grpc.CallOption (missing method after)compiler[InvalidIfaceAssign](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#InvalidIfaceAssign)
```

**Comment by xnkjj** [comment]
@khanakia 
This repository [google-ads-pb](https://github.com/shenzhencenter/google-ads-pb) does not contain functionality to fetch access token by using refresh token. Before you call Google Ads API through this client, you need to do some extra work to ensure that the access token is available.

About your question, I suggest you refer to [this endpoint ](https://developers.google.com/identity/protocols/oauth2/web-server#offline) or the Google Ads [official documentation](https://developers.google.com/google-ads/api/docs/get-started/make-first-call#rest).
