### ISSUE TITLE
How to get the complete logs?

### ISSUE THREAD

**Issue by aromaldev** [shenzhencenter/google-ads-pb#31]
I want to get the complete API logs ([request](https://developers.google.com/google-ads/api/docs/concepts/field-service#request) and[ response](https://developers.google.com/google-ads/api/docs/concepts/field-service#response) with[ request-id](https://developers.google.com/google-ads/api/docs/concepts/call-structure#request-id) and[ request header](https://developers.google.com/google-ads/api/docs/concepts/call-structure#request_headers)) generated while executing the code written using this library.

Reference in PHP SDK :
https://developers.google.com/google-ads/api/docs/client-libs/php/logging

**Comment by jimmyl02** [comment]
I had a similar question and you can see my solution here if it's helpful. the tl;dr is that you need to convert the error into a grpc status using `setatus.Convert`

https://github.com/shenzhencenter/google-ads-pb/issues/24
